FROM apache/airflow:2.9.1-python3.9
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
    
USER airflow

COPY --chown=airflow:root ./dags /opt/airflow/dags
COPY --chown=airflow:root ./requirements.txt /opt/airflow/requirements.txt

RUN pip install -r /opt/airflow/requirements.txt
RUN pip install python-snappy xlrd

CMD ["python", "dags/dagetl.py"]